name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js and Cache Yarn dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: Communeo_Marketplace/api/yarn.lock  # ✅ Correct path for backend yarn.lock

      # 3. Install backend dependencies
      - name: Install dependencies
        run: |
          cd api
          yarn install

      # 4. Lint the code (Optional)
      - name: Lint (Optional)
        run: |
          cd api
          yarn test

      # 5. Run Tests (If applicable)
      - name: Run Tests (If applicable)
        run: |
          cd api
          yarn test || echo "No tests found, skipping..."

      # 6. You don't need to start the server in CI unless necessary
      # If running the server is part of your test, you can keep this.
      # Otherwise, remove this section for CI-only testing.
      - name: Start Backend Server (Optional)
        run: |
          cd api
          yarn start &
